# This workflow will install Python dependencies and run tests with a single version of Python

name: unit-tests

on: [push]

jobs:
  run-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pytest
    - name: Test with pytest
      run: |
        pytest
